// ─── Default Plugin Registration ────────────────────────────
// Registers all default plugins into pluginRegistry so they are
// available immediately without needing a database or marketplace.
// This is a PANOPTIS-specific addition to make the demo work out-of-box.

import { pluginRegistry } from "./PluginRegistry";
import { DeclarativePlugin } from "./loaders/DeclarativePlugin";
import type { PluginManifest } from "./PluginManifest";

const DEFAULT_MANIFESTS: PluginManifest[] = [
    {
        id: "aviation",
        name: "Aviation",
        version: "1.0.0",
        description: "Live aircraft tracking via ADS-B",
        trust: "verified",
        format: "declarative",
        entry: "/api/plugins/aviation",
        type: "data-layer",
        capabilities: ["data:own", "ui:detail-panel", "globe:overlay"],
        category: "intelligence",
        dataSource: {
            url: "/api/plugins/aviation",
            method: "GET",
            format: "json",
            pollInterval: 30000,
            arrayPath: "states",
        },
        fieldMapping: {
            id: "icao24",
            latitude: "latitude",
            longitude: "longitude",
            label: "callsign",
            heading: "true_track",
            speed: "velocity",
            altitude: "geo_altitude",
        },
        rendering: { color: "#22d3ee", entityType: "point", clusterEnabled: true },
    },
    {
        id: "maritime",
        name: "Maritime",
        version: "1.0.0",
        description: "Ship tracking via AIS",
        trust: "verified",
        format: "declarative",
        entry: "/api/plugins/maritime",
        type: "data-layer",
        capabilities: ["data:own", "ui:detail-panel", "globe:overlay"],
        category: "intelligence",
        dataSource: {
            url: "/api/plugins/maritime",
            method: "GET",
            format: "json",
            pollInterval: 60000,
            arrayPath: "vessels",
        },
        fieldMapping: {
            id: "mmsi",
            latitude: "latitude",
            longitude: "longitude",
            label: "name",
            heading: "heading",
            speed: "speed",
        },
        rendering: { color: "#3b82f6", entityType: "point", clusterEnabled: true },
    },
    {
        id: "military-aviation",
        name: "Military Aviation",
        version: "1.0.0",
        description: "Military aircraft tracking",
        trust: "verified",
        format: "declarative",
        entry: "/api/plugins/military-aviation",
        type: "data-layer",
        capabilities: ["data:own", "ui:detail-panel", "globe:overlay"],
        category: "intelligence",
        dataSource: {
            url: "/api/plugins/military-aviation",
            method: "GET",
            format: "json",
            pollInterval: 30000,
            arrayPath: "aircraft",
        },
        fieldMapping: {
            id: "hex",
            latitude: "lat",
            longitude: "lon",
            label: "flight",
            heading: "heading",
            speed: "gs",
            altitude: "alt_baro",
        },
        rendering: { color: "#ef4444", entityType: "point", clusterEnabled: true },
    },
    {
        id: "wildfire",
        name: "Wildfires",
        version: "1.0.0",
        description: "Global wildfire monitoring",
        trust: "verified",
        format: "declarative",
        entry: "/api/plugins/wildfire",
        type: "data-layer",
        capabilities: ["data:own", "ui:detail-panel", "globe:overlay"],
        category: "intelligence",
        dataSource: {
            url: "/api/plugins/wildfire",
            method: "GET",
            format: "json",
            pollInterval: 300000,
            arrayPath: "events",
        },
        fieldMapping: {
            id: "id",
            latitude: "geometries.0.coordinates.1",
            longitude: "geometries.0.coordinates.0",
            label: "title",
        },
        rendering: { color: "#f97316", entityType: "point", clusterEnabled: true },
    },
    {
        id: "camera",
        name: "Cameras",
        version: "1.0.0",
        description: "Public camera feeds",
        trust: "verified",
        format: "static",
        entry: "/api/plugins/camera",
        type: "data-layer",
        capabilities: ["data:own", "ui:detail-panel", "globe:overlay"],
        category: "intelligence",
    },
    {
        id: "borders",
        name: "Borders",
        version: "1.0.0",
        description: "Country borders",
        trust: "verified",
        format: "static",
        entry: "/api/plugins/borders",
        type: "data-layer",
        capabilities: ["data:own", "ui:detail-panel", "globe:overlay"],
        category: "intelligence",
    },
    {
        id: "osm-search",
        name: "OSM Search",
        version: "1.0.0",
        description: "OpenStreetMap search",
        trust: "verified",
        format: "declarative",
        entry: "/api/plugins/osm-search",
        type: "data-layer",
        capabilities: ["data:own", "ui:detail-panel", "globe:overlay"],
        category: "intelligence",
    },
    {
        id: "earthquakes",
        name: "Earthquakes",
        version: "1.0.0",
        description: "Seismic activity",
        trust: "verified",
        format: "declarative",
        entry: "/api/earthquake",
        type: "data-layer",
        capabilities: ["data:own", "ui:detail-panel", "globe:overlay"],
        category: "intelligence",
        dataSource: {
            url: "/api/earthquake",
            method: "GET",
            format: "geojson",
            pollInterval: 120000,
            arrayPath: "features",
        },
        fieldMapping: {
            id: "id",
            latitude: "geometry.coordinates.1",
            longitude: "geometry.coordinates.0",
            label: "properties.title",
            altitude: "geometry.coordinates.2",
            timestamp: "properties.time",
        },
        rendering: { color: "#eab308", entityType: "point", clusterEnabled: true },
    },
    {
        id: "satellite",
        name: "Satellites",
        version: "1.0.0",
        description: "Orbital satellite tracking",
        trust: "verified",
        format: "declarative",
        entry: "/api/plugins/satellite",
        type: "data-layer",
        capabilities: ["data:own", "ui:detail-panel", "globe:overlay"],
        category: "intelligence",
        dataSource: {
            url: "/api/plugins/satellite",
            method: "GET",
            format: "json",
            pollInterval: 300000,
            arrayPath: "satellites",
        },
        fieldMapping: {
            id: "id",
            latitude: "latitude",
            longitude: "longitude",
            label: "name",
            altitude: "altitude",
        },
        rendering: { color: "#a855f7", entityType: "point", clusterEnabled: true },
    },
    {
        id: "daynight",
        name: "Day/Night",
        version: "1.0.0",
        description: "Day/night terminator",
        trust: "verified",
        format: "static",
        entry: "/api/plugins/daynight",
        type: "data-layer",
        capabilities: ["data:own", "ui:detail-panel", "globe:overlay"],
        category: "intelligence",
    },
    {
        id: "conflict-zones",
        name: "Conflict Zones",
        version: "1.0.0",
        description: "Active conflict monitoring",
        trust: "verified",
        format: "declarative",
        entry: "/api/plugins/conflict-zones",
        type: "data-layer",
        capabilities: ["data:own", "ui:detail-panel", "globe:overlay"],
        category: "intelligence",
        dataSource: {
            url: "/api/plugins/conflict-zones",
            method: "GET",
            format: "json",
            pollInterval: 3600000,
            arrayPath: "data",
        },
        fieldMapping: {
            id: "id",
            latitude: "latitude",
            longitude: "longitude",
            label: "country",
            heading: "event_type",
            speed: "fatalities",
            altitude: "events",
        },
        rendering: { color: "#dc2626", entityType: "point", clusterEnabled: true },
    },
    {
        id: "volcanoes",
        name: "Volcanoes",
        version: "1.0.0",
        description: "Volcanic activity",
        trust: "verified",
        format: "declarative",
        entry: "/api/plugins/volcanoes",
        type: "data-layer",
        capabilities: ["data:own", "ui:detail-panel", "globe:overlay"],
        category: "intelligence",
        dataSource: {
            url: "/api/plugins/volcanoes",
            method: "GET",
            format: "json",
            pollInterval: 3600000,
            arrayPath: "data",
        },
        fieldMapping: {
            id: "id",
            latitude: "latitude",
            longitude: "longitude",
            label: "name",
        },
        rendering: { color: "#dc2626", entityType: "point", clusterEnabled: true },
    },
    {
        id: "airports",
        name: "Airports",
        version: "1.0.0",
        description: "Global airports",
        trust: "verified",
        format: "declarative",
        entry: "/api/plugins/airports",
        type: "data-layer",
        capabilities: ["data:own", "ui:detail-panel", "globe:overlay"],
        category: "intelligence",
        dataSource: {
            url: "/api/plugins/airports",
            method: "GET",
            format: "json",
            pollInterval: 86400000,
            arrayPath: "airports",
        },
        fieldMapping: {
            id: "id",
            latitude: "latitude",
            longitude: "longitude",
            label: "name",
        },
        rendering: { color: "#10b981", entityType: "point", clusterEnabled: true },
    },
    {
        id: "international-sanctions",
        name: "Sanctions",
        version: "1.0.0",
        description: "International sanctions data",
        trust: "verified",
        format: "declarative",
        entry: "/api/plugins/international-sanctions",
        type: "data-layer",
        capabilities: ["data:own", "ui:detail-panel", "globe:overlay"],
        category: "intelligence",
        dataSource: {
            url: "/api/plugins/international-sanctions",
            method: "GET",
            format: "json",
            pollInterval: 86400000,
            arrayPath: "data",
        },
        fieldMapping: {
            id: "id",
            latitude: "latitude",
            longitude: "longitude",
            label: "name",
        },
        rendering: { color: "#f59e0b", entityType: "point", clusterEnabled: true },
    },
    {
        id: "gps-jamming",
        name: "GPS Jamming",
        version: "1.0.0",
        description: "GPS interference detection",
        trust: "verified",
        format: "declarative",
        entry: "/api/plugins/gps-jamming",
        type: "data-layer",
        capabilities: ["data:own", "ui:detail-panel", "globe:overlay"],
        category: "intelligence",
        dataSource: {
            url: "/api/plugins/gps-jamming",
            method: "GET",
            format: "json",
            pollInterval: 300000,
            arrayPath: "reports",
        },
        fieldMapping: {
            id: "id",
            latitude: "latitude",
            longitude: "longitude",
            label: "location",
        },
        rendering: { color: "#ec4899", entityType: "point", clusterEnabled: true },
    },
    {
        id: "fortiguard",
        name: "FortiGuard",
        version: "1.0.0",
        description: "Threat intelligence",
        trust: "verified",
        format: "declarative",
        entry: "/api/plugins/fortiguard",
        type: "data-layer",
        capabilities: ["data:own", "ui:detail-panel", "globe:overlay"],
        category: "intelligence",
        dataSource: {
            url: "/api/plugins/fortiguard",
            method: "GET",
            format: "json",
            pollInterval: 3600000,
            arrayPath: "categories",
        },
        fieldMapping: {
            id: "id",
            latitude: "latitude",
            longitude: "longitude",
            label: "name",
        },
        rendering: { color: "#6366f1", entityType: "point", clusterEnabled: true },
    },
    {
        id: "nz-traffic-cameras",
        name: "Traffic Cameras",
        version: "1.0.0",
        description: "NZ traffic cameras",
        trust: "verified",
        format: "static",
        entry: "/api/plugins/nz-traffic-cameras",
        type: "data-layer",
        capabilities: ["data:own", "ui:detail-panel", "globe:overlay"],
        category: "intelligence",
    },
    {
        id: "military-ship",
        name: "Military Ships",
        version: "1.0.0",
        description: "Naval vessel tracking",
        trust: "verified",
        format: "declarative",
        entry: "/api/plugins/military-ship",
        type: "data-layer",
        capabilities: ["data:own", "ui:detail-panel", "globe:overlay"],
        category: "maritime",
        dataSource: {
            url: "/api/plugins/military-ship",
            method: "GET",
            format: "json",
            pollInterval: 60000,
            arrayPath: "vessels",
        },
        fieldMapping: {
            id: "mmsi",
            latitude: "latitude",
            longitude: "longitude",
            label: "name",
            heading: "heading",
            speed: "speed",
        },
        rendering: { color: "#dc2626", entityType: "point", clusterEnabled: true },
    },
    {
        id: "military-satellites",
        name: "Military Satellites",
        version: "1.0.0",
        description: "Military satellite tracking",
        trust: "verified",
        format: "declarative",
        entry: "/api/plugins/military-satellites",
        type: "data-layer",
        capabilities: ["data:own", "ui:detail-panel", "globe:overlay"],
        category: "aviation",
        dataSource: {
            url: "/api/plugins/military-satellites",
            method: "GET",
            format: "json",
            pollInterval: 300000,
            arrayPath: "satellites",
        },
        fieldMapping: {
            id: "id",
            latitude: "latitude",
            longitude: "longitude",
            label: "name",
            altitude: "altitude",
        },
        rendering: { color: "#b91c1c", entityType: "point", clusterEnabled: true },
    },
    {
        id: "border-surveillance",
        name: "Border Surveillance",
        version: "1.0.0",
        description: "Border monitoring",
        trust: "verified",
        format: "declarative",
        entry: "/api/plugins/border-surveillance",
        type: "data-layer",
        capabilities: ["data:own", "ui:detail-panel", "globe:overlay"],
        category: "intelligence",
        dataSource: {
            url: "/api/plugins/border-surveillance",
            method: "GET",
            format: "json",
            pollInterval: 300000,
            arrayPath: "incidents",
        },
        fieldMapping: {
            id: "id",
            latitude: "latitude",
            longitude: "longitude",
            label: "location",
        },
        rendering: { color: "#f97316", entityType: "point", clusterEnabled: true },
    },
    {
        id: "cyber-tracker",
        name: "Cyber Tracker",
        version: "1.0.0",
        description: "Cyber threat monitoring",
        trust: "verified",
        format: "declarative",
        entry: "/api/plugins/cyber-tracker",
        type: "data-layer",
        capabilities: ["data:own", "ui:detail-panel", "globe:overlay"],
        category: "cyber",
        dataSource: {
            url: "/api/plugins/cyber-tracker",
            method: "GET",
            format: "json",
            pollInterval: 300000,
            arrayPath: "threats",
        },
        fieldMapping: {
            id: "id",
            latitude: "latitude",
            longitude: "longitude",
            label: "name",
        },
        rendering: { color: "#ef4444", entityType: "point", clusterEnabled: true },
    },
    {
        id: "drone-detection",
        name: "Drone Detection",
        version: "1.0.0",
        description: "UAV detection",
        trust: "verified",
        format: "declarative",
        entry: "/api/plugins/drone-detection",
        type: "data-layer",
        capabilities: ["data:own", "ui:detail-panel", "globe:overlay"],
        category: "intelligence",
        dataSource: {
            url: "/api/plugins/drone-detection",
            method: "GET",
            format: "json",
            pollInterval: 30000,
            arrayPath: "sightings",
        },
        fieldMapping: {
            id: "id",
            latitude: "latitude",
            longitude: "longitude",
            label: "type",
        },
        rendering: { color: "#84cc16", entityType: "point", clusterEnabled: true },
    },
    {
        id: "weather-tracker",
        name: "Weather Tracker",
        version: "1.0.0",
        description: "Severe weather monitoring",
        trust: "verified",
        format: "declarative",
        entry: "/api/plugins/weather-tracker",
        type: "data-layer",
        capabilities: ["data:own", "ui:detail-panel", "globe:overlay"],
        category: "natural-disaster",
        dataSource: {
            url: "/api/plugins/weather-tracker",
            method: "GET",
            format: "json",
            pollInterval: 300000,
            arrayPath: "weather",
        },
        fieldMapping: {
            id: "id",
            latitude: "latitude",
            longitude: "longitude",
            label: "name",
        },
        rendering: { color: "#06b6d4", entityType: "point", clusterEnabled: true },
    },
];

/**
 * Register all default plugins into pluginRegistry.
 * Call this early (e.g. in AppShell) before pluginManager.init().
 */
export function registerDefaultPlugins(): void {
    for (const manifest of DEFAULT_MANIFESTS) {
        try {
            const plugin = new DeclarativePlugin(manifest);
            pluginRegistry.register(plugin);
        } catch (err) {
            console.warn(`[registerDefaults] Failed to register ${manifest.id}:`, err);
        }
    }
    console.log(`[registerDefaults] Registered ${DEFAULT_MANIFESTS.length} default plugins (v2)`);
}
